### ISSUE TITLE
Consider sharing reason why target is no longer visible.

### ISSUE THREAD

**Issue by lread** [borkdude/api-diff#13]
**Proposal**
When comparing APIs, a target var can be reported as removed.
It would be nice to know the reason why. Here are current possibilities:
1. deleted - the var no longer exists 
2. made private - the var was public, but has become private
3. excluded - the filtering specified to api-diff excluded the target var (we currently only have `:exclude-meta` but might add more in the future)

**Other details** 
I might have inadvertently undone some private reporting via #8, but I think api-diff might have been comparing privates to privates? If so, this would be a refinement.

**Implementation ideas**
As of this writing, we have:
```
test-resources/older/example.clj:6:1: error: example/becomes-private was removed.
test-resources/older/example.clj:8:1: error: example/becomes-nodoc was removed.
test-resources/older/example.clj:11:1: error: example/y was removed.
```

If we were to add the reason:
```
test-resources/older/example.clj:6:1: warn: example/becomes-private was made private.
test-resources/older/example.clj:8:1: warn: example/becomes-nodoc was excluded from diff (meta :no-doc).
test-resources/older/example.clj:11:1: error: example/y was deleted.
```

Future thought: If we do end up with multiple exclusion filters, and a single target was excluded for multiple reasons we'd only show 1 reason.

**Next steps**
I could take this on, if nobody beats me to it.

**Comment by borkdude** [comment]
Good idea! Take it :)
