### ISSUE TITLE
Mention static analysis in README?

### ISSUE THREAD

**Issue by lread** [borkdude/api-diff#6]
Should we mention that api-diff uses clj-kondo static analysis and therefore will not pick up APIs that are generated at load time?  (We can mention it can compensate via custom hooks and has built in support for potemkin import-vars).

([Amazonica](https://github.com/mcohen01/amazonica) is a good example of a lib that does load time API generation.)

If you think this is a good thing to mention I can add in.

**Comment by borkdude** [comment]
Yes. It might be better to move this repo to the clj-kondo org, so it's entirely clear that this is a clj-kondo-based project. What do you think?
